config/routes.rb
Rails.application.routes.draw do

  ## == Devise OAuth ==
devise_for :dusers,
controllers: { omniauth_callbacks: 'dusers/omniauth_callbacks' },
omniauth_providers: %i[events360]

  
  root 'home#landing_page'
  get 'home', to: 'home#index'
  get '/logout', to: 'application#logout'

  get '/validation/:id', to: 'home#validation'
  
  get '/api/change_status/:id', to: 'api#change_status'

  get '/api/', to: 'api#index'
  
  resources :home, only: [] do
    post 'login', :on => :collection
    post 'signup', :on => :collection
    post 'forgotPassword', :on => :collection
    post 'role_selection', :on => :collection
    get 'first_time_user', :on => :collection
  end
  
  resources :user, only: [:index] do
    collection do
      resources :events, only: [:show] do
        resources :slides, only: [:create]
        resources :messages, only: [:create]
      end
    end
  end
  
  resources :client, only: [:index] do
    collection do
      resources :events, only: [:show] do
        resources :negotiations, only: [:create]
        resources :messages, only: [:create]
        resources :slides, only: [:create] do
          resources :comments, only: [:create]
        end
      end
    end
  end
  
  resources :admin, only: [:index] do
    collection do
      resources :events, only: [:show, :update, :new, :create, :edit] do
        resources :negotiations, only: [:create]
        resources :messages, only: [:create]
        resources :announcements, only: [:create]
        resources :slides, only: [:create, :destroy] do
          resources :comments, only: [:create]
        end
      end
      resources :forms, :only => [:show, :create]
    end
  end
  
  resources :slides, only: [] do
    member do
      post 'update_payment_status'
      get 'payment_status'
    end
  end
end

 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET /
  def index
    if is_session_valid?
      redirect_to get_redirect_path
    end
  end
  
  # GET /validation/:id
  def validation
    # u1 = Auth.find_by(:_id => params[:id])
    # typeuser = u1.user_type
    # begin
    #   if "ADMIN".casecmp? typeuser
    #     user = Producer.find_by(:_id => params[:id])
    #     user.is_valid = true
    #     user.save
    #     auth = Auth.find_by(:_id => params[:id])
    #     puts auth.email
    #     auth.is_valid = true
    #     auth.save
    #   elsif "CLIENT".casecmp? typeuser
    #     user = Client.find_by(:_id => params[:id])
    #     user.is_valid = true
    #     user.save
    #     auth = Auth.find_by(:_id => params[:id])
    #     puts auth.email
    #     auth.is_valid = true
    #     auth.save
    #   else
    #     user = Talent.find_by(:_id => params[:id])
    #     user.is_valid = true
    #     user.save
    #     auth = Auth.find_by(:_id => params[:id])
    #     puts "talent"
    #     puts auth.email
    #     auth.is_valid = true
    #     auth.save
    #   end
    #   return redirect_to root_path
    #   #render json: {redirect_path: "User validated!"}, status: 201
    # end
  end

  # POST /home/signup
  # POST /admin/signup
  def signup
    begin
      if new_user?(params[:email])
        create_user(params)
        currentUser = get_user(params[:email], params[:password])
        # UserMailer.send_welcome(params[:email], currentUser._id.to_str).deliver_now
        session[:userEmail] = currentUser.email
        session[:userType] = currentUser.user_type
        session[:userName] = currentUser.name
        session[:userId] = currentUser._id.to_str
        render json: {comment: "Account Created Sucessfully - Login now!"}, status: 400
      else
        render json: {comment: "An account with the given Email already exists!"}, status: 400
      end
    rescue => exception
      puts exception.message
      render json: {comment: "Internal Error!"}, status: 500
    end
  end
  
  # POST /home/login
  def login
    begin
      if correct_user?(params[:email], params[:password])
        currentUser = get_user(params[:email], params[:password])
        if currentUser.is_valid == false
          render json: {comment: "User not validated! Please check your mailbox for validation email."}, status: 400
          return
        elsif currentUser.is_active == false
          render json: {comment: "User is inactive. Contact the admin of the event."}, status: 400
          return
        end
        session[:userEmail] = currentUser.email
        session[:userType] = currentUser.user_type
        session[:userName] = currentUser.name
        session[:userId] = currentUser._id.to_str
        render json: {redirect_path: get_redirect_path}, status: 200
      else
        render json: {comment: "The entered Username or Password is incorrect!"}, status: 400
      end
    rescue Exception => e
      render json: {comment: e.message}, status: 500
    end
  end

  def role_selection

    
    begin
      
      duser = Duser.find_by(_id: session[:userId])
  
      # Handle case if the user doesn't exist
      if duser.nil?
        render json: { error: "User not found" }, status: 404
        return
      end
  
      # Step 2: Check if the user's role is 'new_user'
      if duser.user_type == 'new_user'
        # Step 3: Based on the role parameter, create the appropriate role-based object
        case params[:role].upcase
        when 'ADMIN'
          # Check if Producer already exists, otherwise create
          begin
          producer = Producer.find_by(_id: session[:userId])
          rescue Mongoid::Errors::DocumentNotFound => e
          producer = nil
          end
          session[:userType] = 'ADMIN'
          if producer
            producer.update(name: session[:userName], email: session[:userEmail], is_valid: true)
          else
            Producer.create(_id: session[:userId], name: session[:userName], email: session[:userEmail], is_valid: true)
          end
          redirect_to admin_index_path
  
        when 'CLIENT'
          session[:userType] = 'CLIENT'
          # Check if Client already exists, otherwise create
          begin
          client = Client.find_by(_id: session[:userId])
          rescue Mongoid::Errors::DocumentNotFound => e
          client = nil
          end
          if client
            client.update(name: session[:userName], email: session[:userEmail], is_valid: true)
          else
            Client.create(_id: session[:userId], name: session[:userName], email: session[:userEmail], is_valid: true)
          end
          redirect_to client_index_path

  
        when 'TALENT'
          session[:userType] = 'USER'

          # Check if Talent already exists, otherwise create
          begin
          talent = Talent.find_by(_id: session[:userId])
          rescue Mongoid::Errors::DocumentNotFound => e
            talent = nil
          end
          if talent
            talent.update(name: session[:userName], email: session[:userEmail], is_valid: true)
          else
            Talent.create(_id: session[:userId], name: session[:userName], email: session[:userEmail], is_valid: true)
          end
          redirect_to user_index_path
  
        else
          # Return error if role is invalid
          render json: { error: "Invalid role specified" }, status: 400
          return
        end
  
        # Update the user's role to reflect they have selected a role
        duser.update(user_type: params[:role])
  
      else
        render json: { error: "User is not a new_user" }, status: 400
      end
    rescue => e
      # Catch any unexpected errors and return a 500 server error response
      Rails.logger.error "Error in role_selection: #{e.message}"
      render json: { error: "Something went wrong" }, status: 500
    end
  end
  

  # POST /home/forgotPassword
  def forgotPassword
    # begin
    #   if user_exists?(params[:email])
    #     resetLink = generate_resetlink(params[:email])
    #     UserMailer.password_reset(params[:email], resetLink)
    #     render json: {comment: "A password reset email has been sent to your mailbox!"}, status: 400
    #     return
    #   else
    #     render json: {comment: "No such email exists."}, status: 400
    #   end
    # rescue Exception => e
    #   render json: {comment: e.message}, status: 500
    # end
  end

  def landing_page
    puts "tests"
    respond_to do |format|
      format.html { render :layout => false }
    end
  end
  
  
  
  def get_user email, password
    return Auth.find_by(:email => email, :password => password)
  end
  
  def new_user? email
    if Auth.where(:email => email).blank?
      return true
    end
    
    return false
  end
  
  def correct_user? email, password
    if Auth.where(:email => email, :password => password).present?
      return true
    end
    
    return false
  end

  def user_exists? email
    if Auth.where(:email => email).present?
      return true
    end

    return false
  end

  # def generate_resetlink email
  #   require 'securerandom'
  #   rCode = SecureRandom.hex(32)
  #   rsetCode = AuthReset.create(:resetuuid => rCode)
  #   return rCode
  # end
  
    # You can add any logic needed for first-time users here
    # For example, tracking analytics, setting flags, etc.

  end


  def create_user params
    puts (params)
    user = Auth.create(:name => params[:name], :email => params[:email], :password => params[:password], :user_type => params[:type], :is_valid => true)
    if "ADMIN".casecmp? params[:type]
      Producer.create(:_id => user._id.to_str, :name => user.name, :email => user.email, :is_valid => true)
    elsif "CLIENT".casecmp? params[:type]
      Client.create(:_id => user._id.to_str, :name => user.name, :email => user.email, :is_valid => true)
    else
      Talent.create(:_id => user._id.to_str, :name => user.name, :email => user.email, :is_valid => true)
    end
  end

  def get_redirect_path
    if "ADMIN".casecmp? session[:userType]
      return "/admin"
    elsif "CLIENT".casecmp? session[:userType]
      return "/client"
    else
      return "/user"
    end
  end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/first_time_user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CASTNXT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>
  <body  style="background-color: white !important;">
    
    <div id="main-content" style="background-color: white !important; height: 80vh; ">
       

    <section class="mb-5 mt-4" id="features">
        <section class="mb-5">
        <h3 class="text-center display-5 fw-bold lh-1 mb-5 mt-5"> Welcome to CastNXT </h3>
        </section>
        <section class="mb-5">

        <p class="mb-md-3 lead fs-6 text-center"> You are logging in to CastNXT for the first time. Please select a Role to create an account</p>
        <%= form_with url: role_selection_home_index_path, method: :post do %>

        <div class="d-flex flex-column align-items-center">
          <div class="form-check mb-4 d-flex align-items-center">
            <%= radio_button_tag :role, "admin", false, id: "role_admin", class: "form-check-input me-3" %>
            <label class="form-check-label" for="role_admin">
              <h3 class="my-2">Admin</h3>
            </label>
          </div>
          
          <div class="form-check mb-4 d-flex align-items-center">
            <%= radio_button_tag :role, "client", false, id: "role_client", class: "form-check-input me-3" %>
            <label class="form-check-label" for="role_client">
              <h3 class="my-2">Client</h3>
            </label>
          </div>
          
          <div class="form-check mb-4 d-flex align-items-center">
            <%= radio_button_tag :role, "talent", false, id: "role_talent", class: "form-check-input me-3" %>
            <label class="form-check-label" for="role_talent">
              <h3 class="my-2">Talent</h3>
            </label>
          </div>
        </div>
      
        <div class="text-center mt-5">
          <%= submit_tag "Submit Role", class: "btn btn-primary fw-bold" %>
        </div>
       <% end %>
 
      </section>
      
     </section>
      </div>
      </div>
  </body>
</html>

app/views/home/index.html.erb
<%= javascript_tag do %>
  var properties = <%= raw(@properties.to_json) %>
<% end %>
<div></div>

app/views/home/landing_page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CASTNXT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag  'landing_page', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color: #e3f2fd;">
        <div class="container-fluid">
          <%= link_to root_path, class: 'navbar-brand' do %>
            <strong>CastNXT</strong>
          <% end %>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#login">Login</a>
              </li>
              <li class="nav-item">
                <%= link_to 'Home', root_path, class: 'nav-link active', aria: { current: 'page' } %>
              </li>
              
              
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
            </ul>
            <div class="btn-group dropstart ">
              <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" >
                Dropstart
              </button>
              <ul class="dropdown-menu">
                <!-- Dropdown menu links -->
                <li><a class="dropdown-item" href="#login">Login</a></li>

                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </div>
          </div>
        </div>
    </nav>

      <div class="container">
        <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-info-transparent">
          <div class="col-md-5 p-lg-5 mx-auto my-5">
            <h1 class="display-4 fw-bold text-white">CastNXT</h1>
            <p class="lead fw-bold text-white">Streamline talent recruitment for events and shows with our automated platform. Auditions, placement, replacement, negotiation, handover, and payment—all in one place. Join us for a seamless experience.!</p>
          </div>
          <div class="product-device shadow-sm d-none d-md-block"></div>
          <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
        </div>

        <div class="container-fluid col-xxl-8 px-0 py-5">
          <div class="row flex-lg-row-reverse align-items-center g-5 py-2">
            <div class="col-10 col-sm-12 col-lg-7">
              <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="https://cdn.pixabay.com/photo/2017/04/10/16/55/live-music-2219036__480.jpg" class="d-block w-100 img-fluid" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="https://cdn.pixabay.com/photo/2020/01/15/17/38/fireworks-4768501__480.jpg" class="d-block w-100 img-fluid" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="https://cdn.pixabay.com/photo/2020/06/08/16/19/woman-5275027__480.jpg" class="d-block w-100 img-fluid" alt="...">
                  </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
            </div>
            <div class="col-lg-5">
              <p class="lead ">At <strong>CastNXT</strong>, we understand that finding and managing talents for your events is a complex task. That's why we have created a comprehensive tool that allows you to easily recruit and communicate with talents and clients, so you can focus on planning the perfect event.
              </p>
            </div>
          </div>
        </div>
                 <h1 class="text-center display-5 fw-bold lh-1 mb-5 mt-5"> Sign Up </h1>
 <div class="row">
            <div class="col-lg-4 col-md-6 col-12 text-center">
              <h3 class="my-4">Admin</h3>
              <p class="mb-md-3 lead fs-6">Looking to simplify talent recruitment for your event? Our automated platform handles the entire process, from auditions to payment. Save time and effort while finding the perfect talent for your show. Join us today.
              </p>
              <a class="btn btn-primary fw-bold" href="/home">Login / Register</a>
            </div>
            <div class="col-lg-4 col-md-6 col-12 text-center">
              <h3 class="my-4">Client</h3>
              <p class="mb-md-3 lead fs-6">Find the perfect talent for your show with our automated platform. Effortlessly browse, audition, negotiate, and hire—all in one place. Join us to discover top-tier talent and make your show a hit. </p>
              <a class="btn btn-primary fw-bold" href="/home">Login / Register</a>
            </div>
            <div class="col-lg-4 col-md-6 col-12 text-center">
              <h3 class="my-4">Users</h3>
              <p class="mb-md-3 lead fs-6">Ready to showcase your talent? Register for events on our automated platform. Effortlessly audition, negotiate, and get paid—all in one place. Join us to take your performance to the next level.</p>
              <a class="btn btn-primary fw-bold" href="/home">Login / Register</a>
            </div>
          </div>
        </section>
        <hr class="my-5" />
        <section class="mb-5" >
        <!-- Add the "Login with Event 360" button here -->
  <div class="text-center mt-5">
  
   <%= button_to 'Sign in with Events360', duser_events360_omniauth_authorize_path, 
            method: :post, data: {turbo: false}, form: { id: 'events360_login_form' }, class: 'btn btn-success fw-bold' %>
        
     </section>
      </div>
  </body>
</html>